### ISSUE TITLE
Unable to verify user credentials

### ISSUE THREAD

**Issue by pacoorozco** [cl-tzuhan/Cumulus#3] opened 2012-10-06 08:07 UTC
I can connect to my Cloudstack 3.0.4. Every tiem i try it I've got an error message like this:
"Unable to verify user credentials"
I'm using this URL: cloud.upc.edu
Can you give me some advice?

**Comment by cl-tzuhan** [comment] 2012-10-09 01:45
Hi pakusland,

Thanks for the question.  I just checked with our in-house instance, and I was able to successfully provision Cumulus against CloudStack 3.0.5.  I don't have a 3.0.4 instance to check against, but from an api point of view, I am not aware of any api changes in that version that would cause a login problem.

I am unfamiliar with cloud.upc.edu, but a "Unable to verify user credentials" message suggests to me that perhaps the connection to the CloudStack was successful, but the user name, domain name, or password might be the cause.  Without knowing what your credentials and/or status are, I can't suggest any specific solutions, but I would try checking the following things off the top of my head:
1. Is Cumulus the latest version? (I used 1.2 142)
2. If HTTPS is needed to connect to cloud.upc.edu (seems like it is?), make sure the url/ip entered into the account screen is prefixed by "https://"
3. If the user is in a domain, is the domain field entered correctly?
4. Is the username entered correctly?
5. Is the password entered correctly (case-sensitive)?
6. Can you login to cloud.upc.edu via the Web UI?  Is the user disabled or locked out on CloudStack?  (If you can login via the CloudStack Web UI, you should be fine)
7. Does the user have api keys generated? (Cumulus should give you an error message to this effect if it is able to login but cannot find api keys, but just to be safe)
8. Does cloud.upc.edu somehow block api request from the general Internet?  (I would assume only whoever runs cloud.upc.edu can tell you this.  If api requests from the Internet are not allowed, Cumulus will not be able to provision against this CloudStack)

Hope something helps,

Tzu-Han Hsu

**Comment by cl-tzuhan** [comment] 2013-03-04 09:56
No follow-up questions, so closing issue.

**Closed as completed by cl-tzuhan** 2013-03-04 09:56 UTC
